### ISSUE TITLE
DTO 네이밍 통일방안 제안

### ISSUE THREAD

**Issue by JaeHyeonKim19** [mash-up-kr/Potato-Invitation-Backend#30]
# DTO 네이밍 통일방안 제안

## 현 상황

현재 DTO네이밍시 두 사람이 다른 형식을 사용하고 있음
- 예
  - 재현: `InvitationAddressRequestDTO` 등
  - 수연: `ResDetailInvitationDTO` 등

위 예를 형식으로 나눠보면
1. `{DTO에 포함된 정보}{요청/응답}DTO`
2. `{요청/응답}{DTO에 포함된 정보}DTO`
와 같다.

## 제안

저는 위 두 형식 중 1번형식을 제안합니다. 1번 형식에 해당하는 형식인 `InvitationAddressRequestDTO`를 직역하면 `초대장주소요청DTO`와 같이 자연스러운 어순을 가지게 된다고 생각합니다. 반면 2번의 `ResDetailInvitationDTO`의 경우 `응답상세정보초대장DTO`와 같이 어색한 어순을 가진다고 생각하고 이에따라 1번형식이 더 자연스럽다고 생각합니다.  
  
하지만 꼭 1번이 아니어도 어떤 형식이든 통일되기만 하면 좋다고 생각합니다. 해당 제안에 대해서 자유롭게 의견 댓글로 주시면 감사하겠습니다.

**Comment by kwonsye** [comment]
제안해주신 것 처럼 어순에 맞게 1번 방식으로 통일하는 것이 좋을 것 같습니다.

다만 응답/요청에 관한 키워드인 `Response` / `Resquest` 가 네이밍 마지막에 들어가서 해당 Dto 의 응답/요청 역할에 대해 한눈에 알아차리는데 약간의 시간이 더 소요된다고 생각합니다.

따라서 각각의 도메인 하단에 `/dto/request`, `/dto/response` 패키지를 만들어서 dto 클래스들을 역할에 맞게 분리해서 구성하는 것에 대해 제안합니다😊

**Comment by JaeHyeonKim19** [comment]
넵 좋습니다!
