### ISSUE TITLE
초대장 유형 정보 응답

### ISSUE THREAD

**Issue by JaeHyeonKim19** [mash-up-kr/Potato-Invitation-Backend#4]
# 초대장 유형 정보 응답

* 초대장 유형 정보를 보내준다.

<br>

### 완료 조건
- [ ] 초대장 유형 정보 응답 구현
- [ ] 초대장 유형 정보 응답 테스트 코드 작성
- [ ] 초대장 유형 정보 응답 문서 작성

<br> 

## relate to issue
- none

<br>

#### Reference
- none
<br>

## Check List
- [x] 관련 issue가 있다면 추가했나요?
- [x] 유의미한 Label을 추가했나요?

---

**Comment by kwonsye** [comment]
#16 , #36 에서 해당 이슈에 대한 완료했습니다.
