### ISSUE TITLE
백앤드 요청사항 by 웹

### ISSUE THREAD

**Issue by danivelop** [mash-up-kr/Potato-Invitation-Backend#41]
현재 초대장 api 요청시 응답으로

```jsx
{
  "invitationAddressName": string,
  "invitationContents": string,
  "invitationPlaceName": string,
  "invitationRoadAddressName": string,
  "invitationTime": string,
  "invitationTitle": string,
  "templateImageUrl": string,
  "x": number,
  "y": number
}
```

이렇게 응답을 해주는데 초대장 만들때 사용자가 주소를 선택하는 과정에서

1. 주소검색해서 카카오api가 제공해준 주소 선택
2. 온라인같은 경우를 위해 사용자가 직접 입력한 키워드(ex. 은이네집)를 선택

두가지 경우가 있다보니 주소가 커스텀한 주소인지 카카오주소인지 분리 시키는 것이 코드가독성이나 관리측면에서 봤을때 용이하다고 생각합니다
```
{
  "invitationContents": string,
  "invitationTime": string,
  "invitationTitle": string,
  "templateImageUrl": string,
  "customPlaceName": string,
  "map": {
    "invitationAddressName": string,
    "invitationPlaceName": string,
    "invitationRoadAddressName": string,
    "x": number,
    "y": number
  }
}
```

이렇게 응답을 줄 수 있을까요?

customPlaceName은 이름이 생각안나서 임의로 지은 이름이고 백앤드쪽에 맞게 수정해주셔도 되고 사용자가 커스텀주소를 선택했을땐 "map": null 이 될테고 카카오주소를 선택했을땐 "customPlaceName": null 이 될 것 같습니다

**Comment by danivelop** [comment]
## 백앤드 답변
([notion](https://www.notion.so/by-94e48ec83913444ab0fc3a1a04812039)에 답변 해주신거 옮김)

피드백 늦은점 죄송합니다. 저도 해당 내용에대해서 고민을 해봤는데요. 결론부터 말씀드리면 기존 응답을 활용하여 프론트에서 판단하는게 맞는거 같습니다. 현재 말씀해주신 포인트는 유저가 커스텀 주소를 사용했냐 지도에서 제공하는 주소를 선택했냐에 따라 프론트에서 지도를 보여줄지 말지를 결정해야하기 때문에 해당 부분에 대한 내용이 필요하다인 것 같은데요. 저는 조금 다르게 생각합니다. 커스텀 주소를 사용했을 때 지도를 안띄워 주는 것은 커스텀 주소를 선택해서라기 보단 커스텀 주소를 사용할 경우 주소에 대한 정보가 없기 때문입니다. 즉 본질은 주소에 대한 정보가 있는가 없는가라고 생각합니다. 따라서 해당 내용은 프론트에서 서버에서 받는 응답을 가지고 판단하는게 맞다고 생각합니다.

또 만약 말씀해주신대로 진행하게 된다면 서버가 프론트, 안드로이드, 카카오API에 종속적이게 되는 문제가 발생합니다. 만약 프론트에서 지도를 띄워줄지 말지에 대한 판단 기준이 바뀌게 되면 그에 맞춰서 서버 API가 변경되야합니다.(프론트에서 변경가능한 환경과 비교하면 프론트, 백엔드 개발자간의 불필요한 커뮤니케이션을 유발하여 유지보수를 어렵게 합니다.) 또 카카오 API에서 커스텀 주소를 사용하는 경우에도 위도, 경도 등 지도 API에 대한 정보를 제공하게 된다면 그 변경사항에 대한 대응 또한 서버에서 이루어져야 합니다.(이와 같은 상황에서도 안드로이드의 변화에 대해 서버가 영향을 받게되어(안드로이드에대해 종속적이게 되어) 유지보수가 어려워집니다.)

이와같은 이유로 해당내용에 대해서는 프론트에서 판단되어야 한다고 생각합니다. 혹시 추가 의견 있으시면 댓글달아 주시면 감사하겠습니다.

**Comment by danivelop** [comment]
답변 감사드립니다!
궁금한점이 더있어서 몇가지만 더 여쭐께요

> 참고로 제가 기획상의도를 잘못 이해하고 있는 부분이 있을지도 몰라 현재 제가 이해하고 있는 초대장스펙 간단히 쓸께요. 먼저 제가 이해하고 있는 내용은 사용자가 주소검색페이지에서 `우리집`을 검색했다면 주소목록이 뜰텐데 이 목록에서 첫번째목록에는 사용자가 입력한 `우리집`이라는 키워드가 그대로 뜨고(카카오에서 제공받은거 아님) 2번째부터는 카카오에서 `우리집`이라는 키워드를 통해 제공받은 주소목록이 뜨는것으로 알고 있습니다. 만약, 사용자가 가장 상단에 있는 `우리집`을 선택하면 이는 커스텀주소를 선택한 것이고 그 외 다른주소를 선택하면 이는 카카오주소를 선택하는 것으로 알고 있습니다.

답변주신 내용에서 조금더 내용을 추가하면 프론트에서 지도를 보여줄지 말지 결정하는 문제는 지금 내려주시는 데이터만으로도 판단할 수 있고 기능구현할 수 있기때문에 기능 구현의 문제만으로 요청드린것은 아니고 데이터 구조적으로 카카오api를 통해 얻은값과 사용자가 직접입력한 값을 분리시키는것이 코드 관리측면에서 좋다고 생각했습니다

이렇게 생각한 이유는 
사용자가 카카오api에서 제공한 주소를 선택했을때 카카오로부터 받는값은 `invitationAddressName`, `invitationPlaceName`, `invitationRoadAddressName`, `x`, `y`가 있는데 이 값들과 사용자가 직접 입력한 키워드 그 자체의 값(`customPlaceName`)과는 특성이 다르기때문에 분리하는것이 좋다고 생각했습니다.

만약 분리를 하지 않는다면 사용자가 `카카오주소`를 선택했을때는
```
{
  "templateImageUrl": "something",
  "invitationTitle": "[Test]모각코하러 모이자!",
  "invitationContents": "[Test]나의 모임에 초대된 감자 친구들! 우리는 엄청난 서비스를 만들 수 있을거야!",
  "invitationTime": "2020-08-02T17:08:18.475",
  "invitationAddressName": "[Test]서울특별시 송파구 잠실1동 23-5",
  "invitationRoadAddressName": "[Test]서울특별시 송파구 잠실1동 23-5",
  "invitationPlaceName": "[Test]잠실1동 코워킹 스페이스",
  "x": 100.12,
  "y": 200.31
}
```
이렇게 응답이 오고 사용자가 `커스텀주소`를 선택했을때는 제 예상으로는
```
{
  "templateImageUrl": "something",
  "invitationTitle": "[Test]모각코하러 모이자!",
  "invitationContents": "[Test]나의 모임에 초대된 감자 친구들! 우리는 엄청난 서비스를 만들 수 있을거야!",
  "invitationTime": "2020-08-02T17:08:18.475",
  "invitationAddressName": null,
  "invitationRoadAddressName": null,
  "invitationPlaceName": "우리집",
  "x": null,
  "y": null
}
```
이렇게 응답이 올 것으로 생각되는데 그럼 `invitationPlaceName`에는 어떤 경우에는 카카오에서 제공한 값이 들어있을 수도 있고 어떤 경우는 사용자가 직접 입력한 값이 들어가는 경우가 있다보니 일관성도 맞지않고 다른 개발자가 봤을때 헷갈릴 수 있다고 생각합니다. 왜냐하면, 프론트쪽에서도 구현할 때, 사용자가 커스텀 주소를 입력했을때 `null`값이 되는 `invitationAddressName`, `invitationRoadAddressName`, `x`, `y`값들중 아무거나 하나를 선택해 null인지 검사하는..예를들어

```
if (invitationAddressName === null) {
  //커스텀주소 선택한거
} else {
  //카카오주소 선택한거
}
```
이런식으로 구현이 될텐데 그러면 다른 개발자가 봤을때 왜 `invitationAddressName이 null이면 커스컴주소지?` 라는식의 생각을 할 수 있을테고 프론트나 백이나 둘다 `invitationAddressName`, `invitationRoadAddressName`, `x`, `y` 이 값들은 다같이 `null`이거나 다같이 `null`이 아니라는 것을 계속 인지하고 있어야 된다고 생각합니다. 요런 이유들 때문에

사용자가 `카카오주소`를 선택했을때는
```
{
  "templateImageUrl": "something",
  "invitationTitle": "[Test]모각코하러 모이자!",
  "invitationContents": "[Test]나의 모임에 초대된 감자 친구들! 우리는 엄청난 서비스를 만들 수 있을거야!",
  "invitationTime": "2020-08-02T17:08:18.475",
  "customPlaceName": null,
  "map": {
    "invitationAddressName": "[Test]서울특별시 송파구 잠실1동 23-5",
    "invitationRoadAddressName": "[Test]서울특별시 송파구 잠실1동 23-5",
    "invitationPlaceName": "[Test]잠실1동 코워킹 스페이스",
    "x": 100.12,
    "y": 200.31
  }
}
```
을 응답해주고 사용자가 `커스텀주소`를 선택했다면
```
{
  "templateImageUrl": "something",
  "invitationTitle": "[Test]모각코하러 모이자!",
  "invitationContents": "[Test]나의 모임에 초대된 감자 친구들! 우리는 엄청난 서비스를 만들 수 있을거야!",
  "invitationTime": "2020-08-02T17:08:18.475",
  "customPlaceName": "우리집",
  "map": null
}
```
과 같이 응답해주는것이 좋을 것 같다고 생각했습니다!

그리고 답변 주신 내용중 몇가지 궁금한게 있습니다

1.  `만약 프론트에서 지도를 띄워줄지 말지에 대한 판단 기준이 바뀌게 되면 그에 맞춰서 서버 API가 변경되야합니다.` 이부분에서 지도를 띄워줄지 말지에 대한 판단 기준이 어떤 기준을 말씀하신건지 그리고 어떤 API인지 이해를 못했습니다

2.  `카카오 API에서 커스텀 주소를 사용하는 경우에도 위도, 경도 등 지도 API에 대한 정보를 제공하게 된다면 그 변경사항에 대한 대응 또한 서버에서 이루어져야 합니다.` 이부분도 저는 사용자가 커스텀주소를 선택한다는 것은 카카오에서 제공하는 데이터는 안쓰는것으로 이해하고 있어서 `카카오 API에서 커스텀 주소를 사용`한다는 부분을 이해못했습니다ㅠㅠ

제가 저희 초대장 기획의도를 잘못알고 있는 부분이 있을수도 있기때문에 이런부분도 고려해주시면 감사하겠습니다

**Comment by danivelop** [comment]
한가지더 추가!! 
마이너한거긴 합니다만

이것도 토욜날 잠깐 말씀드렸긴 한데 초대장 데이터 요청하는 것에 대해서 없는 초대장id로 요청시 이는 사용자가 요청한 데이터가 서버에 없는 부분이고 서버에러가 아니기 때문에 404에러를 응답해주는게 맞는것 같습니다!(현재는 500에러 응답). 이부분도 한번 확인 부탁드릴께요

**Comment by JaeHyeonKim19** [comment]
> 한가지더 추가!!
> 마이너한거긴 합니다만
> 
> 이것도 토욜날 잠깐 말씀드렸긴 한데 초대장 데이터 요청하는 것에 대해서 없는 초대장id로 요청시 이는 사용자가 요청한 데이터가 서버에 없는 부분이고 서버에러가 아니기 때문에 404에러를 응답해주는게 맞는것 같습니다!(현재는 500에러 응답). 이부분도 한번 확인 부탁드릴께요

클라이언트 입장에서는 해당 초대장에 대한 요청이라 페이지 개념으로 생각할 수 있지만 어디까지나 api 요청이고 해당 api 요청은 웹 뿐만 아니라 다른 클라이언트(안드 또는 ios)에서 다양한 상황에 쓸수 있다고 생각합니다. 그런 상황들에서도 404라고 생각할 수 있는지 궁금합니다. 위키백과 http에서는 404에러를 `문서를 찾을 수 없음. 서버가 요청한 파일이나 스크립트를 찾지 못함.`라고 설명하고 있습니다. 저는 api 응답결과가 문서, 파일, 스크립트에 해당한다고는 생각하지 않습니다. 또한 없는 정보에 대한 요청은 DB에러에 해당한다고 생각하기 때문에 500이라고 생각합니다.

물론 현재 주어진 상황만 놓고 봤을 때는 404라고 생각할 수 도 있습니다. 하지만 서버관점에서 여러 상황을 살피면 404라고 생각하기 어렵다고 생각합니다. 초기부터 설계를 잘하지 않으면 후에 문제점이 발견되었을 때는 수정하기 상당히 까다롭습니다. 그러한 이유로 설계의도를 명확하게 하려는 점 이해해주시면 감사하겠습니다.

**Comment by JaeHyeonKim19** [comment]
> 한가지더 추가!!
> 마이너한거긴 합니다만
> 
> 이것도 토욜날 잠깐 말씀드렸긴 한데 초대장 데이터 요청하는 것에 대해서 없는 초대장id로 요청시 이는 사용자가 요청한 데이터가 서버에 없는 부분이고 서버에러가 아니기 때문에 404에러를 응답해주는게 맞는것 같습니다!(현재는 500에러 응답). 이부분도 한번 확인 부탁드릴께요

넵. 다시 한번 찾아보니 그게 좋을꺼 같네요. 반영해놓도록 하겠습니다.

**Comment by JaeHyeonKim19** [comment]
> 답변 감사드립니다!
> 궁금한점이 더있어서 몇가지만 더 여쭐께요
> 
> > 참고로 제가 기획상의도를 잘못 이해하고 있는 부분이 있을지도 몰라 현재 제가 이해하고 있는 초대장스펙 간단히 쓸께요. 먼저 제가 이해하고 있는 내용은 사용자가 주소검색페이지에서 `우리집`을 검색했다면 주소목록이 뜰텐데 이 목록에서 첫번째목록에는 사용자가 입력한 `우리집`이라는 키워드가 그대로 뜨고(카카오에서 제공받은거 아님) 2번째부터는 카카오에서 `우리집`이라는 키워드를 통해 제공받은 주소목록이 뜨는것으로 알고 있습니다. 만약, 사용자가 가장 상단에 있는 `우리집`을 선택하면 이는 커스텀주소를 선택한 것이고 그 외 다른주소를 선택하면 이는 카카오주소를 선택하는 것으로 알고 있습니다.
> 
> 답변주신 내용에서 조금더 내용을 추가하면 프론트에서 지도를 보여줄지 말지 결정하는 문제는 지금 내려주시는 데이터만으로도 판단할 수 있고 기능구현할 수 있기때문에 기능 구현의 문제만으로 요청드린것은 아니고 데이터 구조적으로 카카오api를 통해 얻은값과 사용자가 직접입력한 값을 분리시키는것이 코드 관리측면에서 좋다고 생각했습니다
> 
> 이렇게 생각한 이유는
> 사용자가 카카오api에서 제공한 주소를 선택했을때 카카오로부터 받는값은 `invitationAddressName`, `invitationPlaceName`, `invitationRoadAddressName`, `x`, `y`가 있는데 이 값들과 사용자가 직접 입력한 키워드 그 자체의 값(`customPlaceName`)과는 특성이 다르기때문에 분리하는것이 좋다고 생각했습니다.
> 
> 만약 분리를 하지 않는다면 사용자가 `카카오주소`를 선택했을때는
> 
> ```
> {
>   "templateImageUrl": "something",
>   "invitationTitle": "[Test]모각코하러 모이자!",
>   "invitationContents": "[Test]나의 모임에 초대된 감자 친구들! 우리는 엄청난 서비스를 만들 수 있을거야!",
>   "invitationTime": "2020-08-02T17:08:18.475",
>   "invitationAddressName": "[Test]서울특별시 송파구 잠실1동 23-5",
>   "invitationRoadAddressName": "[Test]서울특별시 송파구 잠실1동 23-5",
>   "invitationPlaceName": "[Test]잠실1동 코워킹 스페이스",
>   "x": 100.12,
>   "y": 200.31
> }
> ```
> 
> 이렇게 응답이 오고 사용자가 `커스텀주소`를 선택했을때는 제 예상으로는
> 
> ```
> {
>   "templateImageUrl": "something",
>   "invitationTitle": "[Test]모각코하러 모이자!",
>   "invitationContents": "[Test]나의 모임에 초대된 감자 친구들! 우리는 엄청난 서비스를 만들 수 있을거야!",
>   "invitationTime": "2020-08-02T17:08:18.475",
>   "invitationAddressName": null,
>   "invitationRoadAddressName": null,
>   "invitationPlaceName": "우리집",
>   "x": null,
>   "y": null
> }
> ```
> 
> 이렇게 응답이 올 것으로 생각되는데 그럼 `invitationPlaceName`에는 어떤 경우에는 카카오에서 제공한 값이 들어있을 수도 있고 어떤 경우는 사용자가 직접 입력한 값이 들어가는 경우가 있다보니 일관성도 맞지않고 다른 개발자가 봤을때 헷갈릴 수 있다고 생각합니다. 왜냐하면, 프론트쪽에서도 구현할 때, 사용자가 커스텀 주소를 입력했을때 `null`값이 되는 `invitationAddressName`, `invitationRoadAddressName`, `x`, `y`값들중 아무거나 하나를 선택해 null인지 검사하는..예를들어
> 
> ```
> if (invitationAddressName === null) {
>   //커스텀주소 선택한거
> } else {
>   //카카오주소 선택한거
> }
> ```
> 
> 이런식으로 구현이 될텐데 그러면 다른 개발자가 봤을때 왜 `invitationAddressName이 null이면 커스컴주소지?` 라는식의 생각을 할 수 있을테고 프론트나 백이나 둘다 `invitationAddressName`, `invitationRoadAddressName`, `x`, `y` 이 값들은 다같이 `null`이거나 다같이 `null`이 아니라는 것을 계속 인지하고 있어야 된다고 생각합니다. 요런 이유들 때문에
> 
> 사용자가 `카카오주소`를 선택했을때는
> 
> ```
> {
>   "templateImageUrl": "something",
>   "invitationTitle": "[Test]모각코하러 모이자!",
>   "invitationContents": "[Test]나의 모임에 초대된 감자 친구들! 우리는 엄청난 서비스를 만들 수 있을거야!",
>   "invitationTime": "2020-08-02T17:08:18.475",
>   "customPlaceName": null,
>   "map": {
>     "invitationAddressName": "[Test]서울특별시 송파구 잠실1동 23-5",
>     "invitationRoadAddressName": "[Test]서울특별시 송파구 잠실1동 23-5",
>     "invitationPlaceName": "[Test]잠실1동 코워킹 스페이스",
>     "x": 100.12,
>     "y": 200.31
>   }
> }
> ```
> 
> 을 응답해주고 사용자가 `커스텀주소`를 선택했다면
> 
> ```
> {
>   "templateImageUrl": "something",
>   "invitationTitle": "[Test]모각코하러 모이자!",
>   "invitationContents": "[Test]나의 모임에 초대된 감자 친구들! 우리는 엄청난 서비스를 만들 수 있을거야!",
>   "invitationTime": "2020-08-02T17:08:18.475",
>   "customPlaceName": "우리집",
>   "map": null
> }
> ```
> 
> 과 같이 응답해주는것이 좋을 것 같다고 생각했습니다!
> 
> 그리고 답변 주신 내용중 몇가지 궁금한게 있습니다
> 
> 1. `만약 프론트에서 지도를 띄워줄지 말지에 대한 판단 기준이 바뀌게 되면 그에 맞춰서 서버 API가 변경되야합니다.` 이부분에서 지도를 띄워줄지 말지에 대한 판단 기준이 어떤 기준을 말씀하신건지 그리고 어떤 API인지 이해를 못했습니다
> 2. `카카오 API에서 커스텀 주소를 사용하는 경우에도 위도, 경도 등 지도 API에 대한 정보를 제공하게 된다면 그 변경사항에 대한 대응 또한 서버에서 이루어져야 합니다.` 이부분도 저는 사용자가 커스텀주소를 선택한다는 것은 카카오에서 제공하는 데이터는 안쓰는것으로 이해하고 있어서 `카카오 API에서 커스텀 주소를 사용`한다는 부분을 이해못했습니다ㅠㅠ
> 
> 제가 저희 초대장 기획의도를 잘못알고 있는 부분이 있을수도 있기때문에 이런부분도 고려해주시면 감사하겠습니다

해당 내용은 추후 회의를 통해서 조율하는게 좋을 것 같습니다.

**Comment by danivelop** [comment]
넵넵ㅎㅎㅎ 늦은시간까지 감사합니다!!

**Comment by JaeHyeonKim19** [comment]
반영완료(#42 )
