### ISSUE TITLE
초대장 공유 url 만들기

### ISSUE THREAD

**Issue by kwonsye** [mash-up-kr/Potato-Invitation-Backend#5]
# 초대장 공유 url 만들기

* 초대할 초대장을 볼 수 있는 공유 url 만들기

<br>

### 완료 조건
- [ ] id 값을 hash 해서 공유 url 만들기
- [ ] url을 통해 해당 id 의 초대장 데이터를 가져오는 API 만들기
- [ ] 테스트 코드 작성하기

<br> 

## relate to issue
- 없습니다.

<br>

#### Reference
- 없습니다.

<br>

## Check List
- [ ] 관련 issue가 있다면 추가했나요?
- [x] 유의미한 Label을 추가했나요?

---

**Comment by JaeHyeonKim19** [comment]
이슈 해결로인한 close
